#!/bin/bash
# Rust-specific Cargo config.toml generator with authentication support
set -euo pipefail

# Input: YAML data with repositories and component_id
# Output: Generated config.toml file content

# Get input data
YAML_DATA="${1:-}"
OUTPUT_FILE="${2:-/dev/stdout}"

if [[ -z "$YAML_DATA" ]]; then
    echo "Error: No YAML data provided" >&2
    exit 1
fi

# Detect yq version
YQ_TYPE="unknown"
yq_path=$(command -v yq 2>/dev/null)
if [[ -n "$yq_path" ]] && head -1 "$yq_path" 2>/dev/null | grep -q "python"; then
    YQ_TYPE="kislyuk"
else
    YQ_TYPE="mikefarah"
fi

# Helper function to query YAML
yq_query() {
    local data="$1"
    local query="$2"
    
    if [[ "$YQ_TYPE" == "kislyuk" ]]; then
        echo "$data" | yq -r "$query" 2>/dev/null || echo ""
    else
        echo "$data" | yq eval "$query" - 2>/dev/null || echo ""
    fi
}

# Get repository count
repo_count=0
if [[ "$YQ_TYPE" == "kislyuk" ]]; then
    repo_count=$(echo "$YAML_DATA" | yq '.repositories | length' 2>/dev/null || echo "0")
else
    repo_count=$(echo "$YAML_DATA" | yq eval '.repositories | length' - 2>/dev/null || echo "0")
fi

# Generate Cargo config.toml content
{
    echo "# Cargo configuration"
    echo "# Generated by ai-devkit"
    
    if [[ "$repo_count" -gt 0 ]]; then
        # Get first repository for main config
        repo_url=$(yq_query "$YAML_DATA" ".repositories[0].url // \"\"")
        auth_ref=$(yq_query "$YAML_DATA" ".repositories[0].auth // \"\"")
        
        if [[ -n "$repo_url" ]] && [[ "$repo_url" != "null" ]] && [[ "$repo_url" != '""' ]]; then
            echo ""
            echo "[source.crates-io]"
            echo "replace-with = \"custom\""
            echo ""
            echo "[source.custom]"
            echo "registry = \"$repo_url\""
            
            # If auth reference exists, resolve credentials from config file
            if [[ -n "$auth_ref" ]] && [[ "$auth_ref" != "null" ]] && [[ "$auth_ref" != '""' ]]; then
                # Config file is always at ~/.ai-devkit/config.yaml in runtime
                CONFIG_FILE="$HOME/.ai-devkit/config.yaml"
                
                if [[ -f "$CONFIG_FILE" ]]; then
                    # Find matching credential
                    username=""
                    password=""
                    token=""
                    
                    # Get credentials array
                    creds_json=""
                    if [[ "$YQ_TYPE" == "kislyuk" ]]; then
                        creds_json=$(cat "$CONFIG_FILE" | yq '.credentials' 2>/dev/null || echo "[]")
                    else
                        creds_json=$(yq eval '.credentials' "$CONFIG_FILE" 2>/dev/null || echo "[]")
                    fi
                    
                    # Find credential with matching id
                    cred_count=0
                    if [[ "$YQ_TYPE" == "kislyuk" ]]; then
                        cred_count=$(echo "$creds_json" | yq 'length' 2>/dev/null || echo "0")
                    else
                        cred_count=$(echo "$creds_json" | yq eval 'length' - 2>/dev/null || echo "0")
                    fi
                    
                    for (( j=0; j<cred_count; j++ )); do
                        cred_id=""
                        if [[ "$YQ_TYPE" == "kislyuk" ]]; then
                            cred_id=$(echo "$creds_json" | yq -r ".[$j].id // \"\"" 2>/dev/null)
                        else
                            cred_id=$(echo "$creds_json" | yq eval ".[$j].id // \"\"" - 2>/dev/null)
                        fi
                        
                        if [[ "$cred_id" == "$auth_ref" ]]; then
                            if [[ "$YQ_TYPE" == "kislyuk" ]]; then
                                username=$(echo "$creds_json" | yq -r ".[$j].username // \"\"" 2>/dev/null)
                                password=$(echo "$creds_json" | yq -r ".[$j].password // \"\"" 2>/dev/null)
                                token=$(echo "$creds_json" | yq -r ".[$j].token // \"\"" 2>/dev/null)
                            else
                                username=$(echo "$creds_json" | yq eval ".[$j].username // \"\"" - 2>/dev/null)
                                password=$(echo "$creds_json" | yq eval ".[$j].password // \"\"" - 2>/dev/null)
                                token=$(echo "$creds_json" | yq eval ".[$j].token // \"\"" - 2>/dev/null)
                            fi
                            break
                        fi
                    done
                    
                    # Generate auth configuration if credentials found
                    if [[ -n "$token" ]]; then
                        # Use token if available
                        echo ""
                        echo "[registries.custom]"
                        echo "token = \"$token\""
                    elif [[ -n "$username" ]] && [[ -n "$password" ]]; then
                        # Use username/password
                        echo ""
                        echo "[http]"
                        echo "timeout = 30"
                        echo ""
                        echo "# Note: For private registries, consider using SSH keys or tokens"
                        echo "# Basic auth support varies by registry"
                    else
                        echo "# WARNING: Credential reference '$auth_ref' not found in config" >&2
                    fi
                else
                    echo "# WARNING: Config file not found, cannot resolve auth reference '$auth_ref'" >&2
                fi
            fi
            
            # Add additional repositories if any
            if [[ "$repo_count" -gt 1 ]]; then
                echo ""
                echo "# Additional registries"
                for (( i=1; i<repo_count; i++ )); do
                    extra_name=$(yq_query "$YAML_DATA" ".repositories[$i].name // \"\"")
                    extra_url=$(yq_query "$YAML_DATA" ".repositories[$i].url // \"\"")
                    if [[ -n "$extra_name" ]] && [[ -n "$extra_url" ]]; then
                        echo "# $extra_name: $extra_url"
                        echo "[registries.$extra_name]"
                        echo "index = \"$extra_url\""
                        echo ""
                    fi
                done
            fi
        fi
    else
        echo ""
        echo "# Using default crates.io registry"
        echo "[source.crates-io]"
        echo "registry = \"https://github.com/rust-lang/crates.io-index\""
    fi
    
    echo ""
    echo "# Build configuration"
    echo "[build]"
    echo "# jobs = 1 # number of parallel build jobs, defaults to # of CPUs"
    echo "# rustc-wrapper = \"sccache\" # use sccache for caching builds"
    echo ""
    echo "[cargo-new]"
    echo "vcs = \"git\""
    echo ""
    echo "# Network configuration"
    echo "[http]"
    echo "timeout = 30"
    echo "multiplexing = false"
} > "$OUTPUT_FILE"