apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-devkit-config-pvc
  namespace: ai-devkit
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-devkit-workspace-pvc
  namespace: ai-devkit
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
