apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claude-code-config-pvc
  namespace: claude-code
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: claude-code-workspace-pvc
  namespace: claude-code
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
